export type LoginLang = "vi" | "en";

export const loginStrings = {
  vi: {
    login: "Đăng nhập",
    register: "Đăng ký",
    tagline: "Đăng nhập để khám phá những điều quan trọng nhất với bạn.",
    welcome: "Chào mừng đến với",
    startAnonymous: "Bắt đầu với ẩn danh",
    anonymousNote: "Không cần tài khoản · Tiến trình lưu trên thiết bị này",
    or: "HOẶC",
    orEmail: "hoặc dùng email",
    continueGoogle: "Tiếp tục với Google",
    signingGoogle: "Đang đăng nhập với Google...",
    name: "Họ tên",
    email: "Email",
    password: "Mật khẩu",
    noAccount: "Chưa có tài khoản?",
    hasAccount: "Đã có tài khoản?",
    passwordTooShort: "Mật khẩu phải có ít nhất 8 ký tự.",
    emailRequired: "Vui lòng nhập email và mật khẩu.",
    genericError: "Đã có lỗi xảy ra. Vui lòng thử lại sau.",
    dismiss: "Đóng thông báo",
    helpAvatarBtn: "Hướng dẫn",
    helpTitle: "Hồ sơ ẩn danh là gì?",
    helpSubtitle: "Bắt đầu ngay — không cần đăng ký tài khoản",
    helpVideo: "Video hướng dẫn",
    helpBody:
      "Mỗi lần bắt đầu ẩn danh, bạn được cấp một hồ sơ khách riêng. Bạn có thể dùng ứng dụng ngay mà không cần email hay mật khẩu. Hãy đăng ký hoặc đăng nhập bằng Google bất cứ lúc nào để có tài khoản thật.",
    helpAria: "Mở trợ giúp về hồ sơ ẩn danh",
  },
  en: {
    login: "Sign in",
    register: "Sign up",
    tagline: "Sign in to discover what matters most.",
    welcome: "Welcome to",
    startAnonymous: "Start anonymously",
    anonymousNote: "No account required · Progress saved on this device",
    or: "OR",
    orEmail: "or use email",
    continueGoogle: "Continue with Google",
    signingGoogle: "Signing in with Google...",
    name: "Name",
    email: "Email",
    password: "Password",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    passwordTooShort: "Password must be at least 8 characters.",
    emailRequired: "Please enter your email and password.",
    genericError: "Something went wrong. Please try again later.",
    dismiss: "Dismiss error",
    helpAvatarBtn: "Guide",
    helpTitle: "What is an anonymous profile?",
    helpSubtitle: "Start instantly — no account registration needed",
    helpVideo: "Tutorial video",
    helpBody:
      "Each time you start anonymously you get your own guest profile. You can use the app right away without an email or password. Sign up or sign in with Google at any time to get a real account.",
    helpAria: "Open help about anonymous profiles",
  },
} as const;
